export const countries: string[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor (Timor-Leste)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  'Eswatini (fmr. "Swaziland")',
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const techFocusAreas: string[] = [
  "Web Development",
  "Mobile App Development",
  "Data Science",
  "Machine Learning",
  "Cloud Computing",
  "DevOps",
  "Frontend",
  "Backend",
  "Full-Stack",
  "UI/UX Design",
  "Game Development",
  "Artificial Intelligence",
  "Cybersecurity",
  "Blockchain",
  "IoT",
  "Big Data",
  "Linux Administration",
  "Database Management",
  "Network Administration",
  "Microservices",
  "Agile Development",
  "Open Source Contribution",
  "Community Building",
  "Tech Education",
  "Data Engineering",
  "Chatbot Development",
  "Ethical Hacking",
  "Computer Vision",
  "Robotics",
  "Augmented Reality (AR)",
  "Virtual Reality (VR)",
  "Windows Administration",
  "Containerization",
  "Testing and QA",
  "NLP",
  "Low-Code Development",
  "No-Code Development",
  "Bioinformatics",
  "Quantum Computing",
  "Embedded Systems",
  "Digital Signal Processing",
  "High-Performance Computing",
  "Distributed Systems",
  "Geographic Information Systems (GIS)",
  "Wearable Tech",
  "E-commerce Development",
  "Healthcare IT",
  "FinTech",
  "EdTech",
  "GreenTech",
  "Smart Cities",
  "Digital Marketing Tech",
  "E-Government",
  "SpaceTech",
  "TransportTech",
  "Tech Evangelism/Advocacy",
];

export const technologies = [
  // Web Development - Frontend Frameworks/Libraries
  { value: "React", label: "React", group: "Web Development - Frontend" },
  { value: "Angular", label: "Angular", group: "Web Development - Frontend" },
  { value: "Vue.js", label: "Vue.js", group: "Web Development - Frontend" },
  { value: "Svelte", label: "Svelte", group: "Web Development - Frontend" },
  { value: "jQuery", label: "jQuery", group: "Web Development - Frontend" },
  { value: "Backbone.js", label: "Backbone.js", group: "Web Development - Frontend" },
  { value: "Ember.js", label: "Ember.js", group: "Web Development - Frontend" },
  { value: "Preact", label: "Preact", group: "Web Development - Frontend" },
  { value: "Aurelia", label: "Aurelia", group: "Web Development - Frontend" },
  { value: "Polymer", label: "Polymer", group: "Web Development - Frontend" },
  { value: "Meteor", label: "Meteor", group: "Web Development - Frontend" },
  { value: "Mithril", label: "Mithril", group: "Web Development - Frontend" },
  { value: "Knockout.js", label: "Knockout.js", group: "Web Development - Frontend" },
  { value: "Dojo", label: "Dojo", group: "Web Development - Frontend" },
  { value: "Nuxt.js", label: "Nuxt.js", group: "Web Development - Frontend" },
  { value: "Gatsby", label: "Gatsby", group: "Web Development - Frontend" },
  { value: "Sapper", label: "Sapper", group: "Web Development - Frontend" },
  { value: "Stencil", label: "Stencil", group: "Web Development - Frontend" },
  { value: "Quasar", label: "Quasar", group: "Web Development - Frontend" },
  { value: "Alpine.js", label: "Alpine.js", group: "Web Development - Frontend" },
  { value: "Blazor", label: "Blazor", group: "Web Development - Frontend" },
  { value: "Marko", label: "Marko", group: "Web Development - Frontend" },
  { value: "SvelteKit", label: "SvelteKit", group: "Web Development - Frontend" },
  { value: "Solid.js", label: "Solid.js", group: "Web Development - Frontend" },
  { value: "Stimulus", label: "Stimulus", group: "Web Development - Frontend" },
  { value: "Stitches", label: "Stitches", group: "Web Development - Frontend" },
  { value: "Tailwind CSS", label: "Tailwind CSS", group: "Web Development - Frontend" },
  { value: "Bootstrap", label: "Bootstrap", group: "Web Development - Frontend" },
  { value: "Material UI", label: "Material UI", group: "Web Development - Frontend" },
  { value: "Bulma", label: "Bulma", group: "Web Development - Frontend" },
  { value: "Chakra UI", label: "Chakra UI", group: "Web Development - Frontend" },
  { value: "Ant Design", label: "Ant Design", group: "Web Development - Frontend" },
  { value: "Foundation", label: "Foundation", group: "Web Development - Frontend" },
  { value: "Semantic UI", label: "Semantic UI", group: "Web Development - Frontend" },
  { value: "UIKit", label: "UIKit", group: "Web Development - Frontend" },
  { value: "PrimeReact", label: "PrimeReact", group: "Web Development - Frontend" },
  { value: "Onsen UI", label: "Onsen UI", group: "Web Development - Frontend" },
  { value: "React Native Web", label: "React Native Web", group: "Web Development - Frontend" },
  { value: "React Bootstrap", label: "React Bootstrap", group: "Web Development - Frontend" },
  { value: "React Router", label: "React Router", group: "Web Development - Frontend" },
  { value: "React Hook Form", label: "React Hook Form", group: "Web Development - Frontend" },
  { value: "React Final Form", label: "React Final Form", group: "Web Development - Frontend" },
  { value: "React Redux", label: "React Redux", group: "Web Development - Frontend" },
  { value: "React Query", label: "React Query", group: "Web Development - Frontend" },
  { value: "React Intl", label: "React Intl", group: "Web Development - Frontend" },
  { value: "React Helmet", label: "React Helmet", group: "Web Development - Frontend" },

  // Web Development - Backend Frameworks
  { value: "Node.js", label: "Node.js", group: "Web Development - Backend" },
  { value: "Express.js", label: "Express.js", group: "Web Development - Backend" },
  { value: "Django", label: "Django", group: "Web Development - Backend" },
  { value: "Laravel", label: "Laravel", group: "Web Development - Backend" },
  { value: "Spring", label: "Spring", group: "Web Development - Backend" },
  { value: "Ruby on Rails", label: "Ruby on Rails", group: "Web Development - Backend" },
  { value: "ASP.NET", label: "ASP.NET", group: "Web Development - Backend" },
  { value: "Flask", label: "Flask", group: "Web Development - Backend" },
  { value: "Symfony", label: "Symfony", group: "Web Development - Backend" },
  { value: "FastAPI", label: "FastAPI", group: "Web Development - Backend" },
  { value: "NestJS", label: "NestJS", group: "Web Development - Backend" },

  // Mobile Development
  { value: "React Native", label: "React Native", group: "Mobile Development" },
  { value: "Flutter", label: "Flutter", group: "Mobile Development" },
  { value: "Ionic", label: "Ionic", group: "Mobile Development" },
  { value: "Xamarin", label: "Xamarin", group: "Mobile Development" },
  { value: "Swift", label: "Swift", group: "Mobile Development" },
  { value: "Kotlin", label: "Kotlin", group: "Mobile Development" },
  { value: "Java", label: "Java", group: "Mobile Development" },
  { value: "Objective-C", label: "Objective-C", group: "Mobile Development" },
  { value: "C#", label: "C#", group: "Mobile Development" },
  { value: "C++", label: "C++", group: "Mobile Development" },
  { value: "Dart", label: "Dart", group: "Mobile Development" },

  // Database Technologies
  { value: "MongoDB", label: "MongoDB", group: "Database Technologies" },
  { value: "PostgreSQL", label: "PostgreSQL", group: "Database Technologies" },
  { value: "MySQL", label: "MySQL", group: "Database Technologies" },
  { value: "MariaDB", label: "MariaDB", group: "Database Technologies" },
  { value: "SQLite", label: "SQLite", group: "Database Technologies" },
  { value: "Redis", label: "Redis", group: "Database Technologies" },
  { value: "Cassandra", label: "Cassandra", group: "Database Technologies" },
  { value: "Elasticsearch", label: "Elasticsearch", group: "Database Technologies" },
  { value: "Oracle", label: "Oracle", group: "Database Technologies" },
  { value: "Microsoft SQL Server", label: "Microsoft SQL Server", group: "Database Technologies" },
  { value: "Couchbase", label: "Couchbase", group: "Database Technologies" },
  { value: "CouchDB", label: "CouchDB", group: "Database Technologies" },
  { value: "Firebase", label: "Firebase", group: "Database Technologies" },
  { value: "Neo4j", label: "Neo4j", group: "Database Technologies" },
  { value: "Realm", label: "Realm", group: "Database Technologies" },
  { value: "RethinkDB", label: "RethinkDB", group: "Database Technologies" },
  { value: "ArangoDB", label: "ArangoDB", group: "Database Technologies" },
  { value: "DynamoDB", label: "DynamoDB", group: "Database Technologies" },
  { value: "FaunaDB", label: "FaunaDB", group: "Database Technologies" },
  { value: "HBase", label: "HBase", group: "Database Technologies" },
  { value: "InfluxDB", label: "InfluxDB", group: "Database Technologies" },
  { value: "Memcached", label: "Memcached", group: "Database Technologies" },
  { value: "RavenDB", label: "RavenDB", group: "Database Technologies" },
  { value: "Riak", label: "Riak", group: "Database Technologies" },
  { value: "Hazelcast", label: "Hazelcast", group: "Database Technologies" },
  { value: "Hive", label: "Hive", group: "Database Technologies" },
  { value: "PouchDB", label: "PouchDB", group: "Database Technologies" },
  { value: "Solr", label: "Solr", group: "Database Technologies" },
  { value: "Teradata", label: "Teradata", group: "Database Technologies" },
  { value: "VoltDB", label: "VoltDB", group: "Database Technologies" },
  { value: "ZooKeeper", label: "ZooKeeper", group: "Database Technologies" },
  { value: "CockroachDB", label: "CockroachDB", group: "Database Technologies" },
  { value: "H2", label: "H2", group: "Database Technologies" },
  { value: "HSQLDB", label: "HSQLDB", group: "Database Technologies" },
  { value: "Kafka", label: "Kafka", group: "Database Technologies" },
  { value: "Kdb+", label: "Kdb+", group: "Database Technologies" },
  { value: "LevelDB", label: "LevelDB", group: "Database Technologies" },
  { value: "Lucene", label: "Lucene", group: "Database Technologies" },

  // Data Science / Machine Learning
  { value: "TensorFlow", label: "TensorFlow", group: "Data Science / Machine Learning" },
  { value: "PyTorch", label: "PyTorch", group: "Data Science / Machine Learning" },
  { value: "Keras", label: "Keras", group: "Data Science / Machine Learning" },
  { value: "Scikit-learn", label: "Scikit-learn", group: "Data Science / Machine Learning" },
  { value: "Apache Spark", label: "Apache Spark", group: "Data Science / Machine Learning" },
  { value: "Apache Flink", label: "Apache Flink", group: "Data Science / Machine Learning" },
  { value: "Apache Hadoop", label: "Apache Hadoop", group: "Data Science / Machine Learning" },
  { value: "Apache Kafka", label: "Apache Kafka", group: "Data Science / Machine Learning" },
  { value: "Apache Cassandra", label: "Apache Cassandra", group: "Data Science / Machine Learning" },
  { value: "Apache Hive", label: "Apache Hive", group: "Data Science / Machine Learning" },
  { value: "Apache HBase", label: "Apache HBase", group: "Data Science / Machine Learning" },
  { value: "Apache MXNet", label: "Apache MXNet", group: "Data Science / Machine Learning" },
  { value: "Apache Mahout", label: "Apache Mahout", group: "Data Science / Machine Learning" },
  { value: "Apache Pig", label: "Apache Pig", group: "Data Science / Machine Learning" },
  { value: "R", label: "R", group: "Data Science / Machine Learning" },
  { value: "Julia", label: "Julia", group: "Data Science / Machine Learning" },
  { value: "MATLAB", label: "MATLAB", group: "Data Science / Machine Learning" },
  { value: "Pandas", label: "Pandas", group: "Data Science / Machine Learning" },
  { value: "NumPy", label: "NumPy", group: "Data Science / Machine Learning" },
  { value: "SciPy", label: "SciPy", group: "Data Science / Machine Learning" },
  { value: "NLTK", label: "NLTK", group: "Data Science / Machine Learning" },
  { value: "OpenCV", label: "OpenCV", group: "Data Science / Machine Learning" },
  { value: "D3.js", label: "D3.js", group: "Data Science / Machine Learning" },
  { value: "Plotly", label: "Plotly", group: "Data Science / Machine Learning" },
  { value: "Bokeh", label: "Bokeh", group: "Data Science / Machine Learning" },
  { value: "Seaborn", label: "Seaborn", group: "Data Science / Machine Learning" },
  { value: "Matplotlib", label: "Matplotlib", group: "Data Science / Machine Learning" },
  { value: "Altair", label: "Altair", group: "Data Science / Machine Learning" },
  { value: "Shiny", label: "Shiny", group: "Data Science / Machine Learning" },
  { value: "Dash", label: "Dash", group: "Data Science / Machine Learning" },
  { value: "Streamlit", label: "Streamlit", group: "Data Science / Machine Learning" },
  { value: "Scrapy", label: "Scrapy", group: "Data Science / Machine Learning" },
  { value: "Beautiful Soup", label: "Beautiful Soup", group: "Data Science / Machine Learning" },
  { value: "Apache Airflow", label: "Apache Airflow", group: "Data Science / Machine Learning" },
  { value: "Apache Beam", label: "Apache Beam", group: "Data Science / Machine Learning" },
  { value: "Apache Arrow", label: "Apache Arrow", group: "Data Science / Machine Learning" },

  // DevOps & Deployment
  { value: "Docker", label: "Docker", group: "DevOps & Deployment" },
  { value: "Kubernetes", label: "Kubernetes", group: "DevOps & Deployment" },
  { value: "Ansible", label: "Ansible", group: "DevOps & Deployment" },
  { value: "Terraform", label: "Terraform", group: "DevOps & Deployment" },
  { value: "Jenkins", label: "Jenkins", group: "DevOps & Deployment" },
  { value: "AWS", label: "AWS", group: "DevOps & Deployment" },
  { value: "Azure", label: "Azure", group: "DevOps & Deployment" },
  { value: "Google Cloud", label: "Google Cloud", group: "DevOps & Deployment" },
  { value: "Heroku", label: "Heroku", group: "DevOps & Deployment" },
  { value: "Netlify", label: "Netlify", group: "DevOps & Deployment" },
  { value: "Vercel", label: "Vercel", group: "DevOps & Deployment" },
  { value: "DigitalOcean", label: "DigitalOcean", group: "DevOps & Deployment" },
  { value: "Linode", label: "Linode", group: "DevOps & Deployment" },
  { value: "Vagrant", label: "Vagrant", group: "DevOps & Deployment" },
  { value: "Puppet", label: "Puppet", group: "DevOps & Deployment" },
  { value: "Chef", label: "Chef", group: "DevOps & Deployment" },
  { value: "SaltStack", label: "SaltStack", group: "DevOps & Deployment" },
  { value: "Nginx", label: "Nginx", group: "DevOps & Deployment" },
  { value: "Apache", label: "Apache", group: "DevOps & Deployment" },
  { value: "HAProxy", label: "HAProxy", group: "DevOps & Deployment" },
  { value: "Kong", label: "Kong", group: "DevOps & Deployment" },
  { value: "Traefik", label: "Traefik", group: "DevOps & Deployment" },
  { value: "Consul", label: "Consul", group: "DevOps & Deployment" },
  { value: "Vault", label: "Vault", group: "DevOps & Deployment" },
  { value: "Prometheus", label: "Prometheus", group: "DevOps & Deployment" },
  { value: "Grafana", label: "Grafana", group: "DevOps & Deployment" },
  { value: "ELK Stack", label: "ELK Stack", group: "DevOps & Deployment" },
  { value: "Datadog", label: "Datadog", group: "DevOps & Deployment" },
  { value: "New Relic", label: "New Relic", group: "DevOps & Deployment" },
  { value: "Sentry", label: "Sentry", group: "DevOps & Deployment" },
  { value: "Logstash", label: "Logstash", group: "DevOps & Deployment" },
  { value: "Kibana", label: "Kibana", group: "DevOps & Deployment" },
  { value: "Loggly", label: "Loggly", group: "DevOps & Deployment" },
  { value: "Papertrail", label: "Papertrail", group: "DevOps & Deployment" },
  { value: "Splunk", label: "Splunk", group: "DevOps & Deployment" },
  { value: "LogDNA", label: "LogDNA", group: "DevOps & Deployment" },
  { value: "Logz.io", label: "Logz.io", group: "DevOps & Deployment" },
  { value: "Sumo Logic", label: "Sumo Logic", group: "DevOps & Deployment" },
  { value: "PagerDuty", label: "PagerDuty", group: "DevOps & Deployment" },
  { value: "Opsgenie", label: "Opsgenie", group: "DevOps & Deployment" },
  { value: "VictorOps", label: "VictorOps", group: "DevOps & Deployment" },
  { value: "OpsDash", label: "OpsDash", group: "DevOps & Deployment" },
  { value: "Opsmatic", label: "Opsmatic", group: "DevOps & Deployment" },
  { value: "Opsview", label: "Opsview", group: "DevOps & Deployment" },

  // Other
  { value: "GraphQL", label: "GraphQL", group: "Other" },
  { value: "REST", label: "REST", group: "Other" },
  { value: "gRPC", label: "gRPC", group: "Other" },
  { value: "gRPC-Gateway", label: "gRPC-Gateway", group: "Other" },
  { value: "gRPC-Web", label: "gRPC-Web", group: "Other" },

  { value: "MemberOnboarding", label: "Member Onboarding & Retention", group: "Community Engagement Strategies" },
  { value: "CommunityFeedback", label: "Community Feedback Mechanisms", group: "Community Engagement Strategies" },
  { value: "CommunityCheckIns", label: "Regular Community Check-ins", group: "Community Engagement Strategies" },

  { value: "Blogging", label: "Blogging & Articles", group: "Content Creation & Sharing" },
  { value: "Webinars", label: "Webinars & Podcasts", group: "Content Creation & Sharing" },
  { value: "Tutorials", label: "Tutorials & How-to Guides", group: "Content Creation & Sharing" },

  { value: "Hackathons", label: "Hackathons", group: "Events & Meetups" },
  { value: "Workshops", label: "Workshops", group: "Events & Meetups" },
  { value: "MeetAndGreets", label: "Community Meet-and-Greets", group: "Events & Meetups" },

  { value: "SpeakingEngagements", label: "Speaking Engagements", group: "Tech Evangelism" },
  { value: "TechRepresentation", label: "Tech Representation at Events", group: "Tech Evangelism" },
  { value: "InfluencerRelations", label: "Building Relations with Influencers", group: "Tech Evangelism" },

  { value: "Mentorship", label: "Mentorship Programs", group: "Mentorship Programs" },

  { value: "OnlineAMAs", label: "Hosting AMAs", group: "Online Forums & Discussions" },
  { value: "TechForums", label: "Participation in Tech Forums", group: "Online Forums & Discussions" },
  { value: "TechDiscussionSpaces", label: "Creating Tech Discussion Spaces", group: "Online Forums & Discussions" },

  { value: "DiversityInTech", label: "Ensuring Diversity in Tech", group: "Advocacy & Representation" },
  { value: "EthicalTech", label: "Advocating for Ethical Tech", group: "Advocacy & Representation" },
  { value: "UnderrepresentedCommunities", label: "Representing Underserved Communities", group: "Advocacy & Representation" },

  { value: "TechFeedback", label: "Gathering Tech Feedback", group: "Feedback & Iteration" },
  { value: "ProductIteration", label: "Iterating on Products", group: "Feedback & Iteration" },
  { value: "BetaTesting", label: "Hosting Beta Testing", group: "Feedback & Iteration" },

  { value: "OpenSourceContribution", label: "Open Source Contribution", group: "Collaboration & Open Source Contribution" },
  { value: "CollaborativeProblemSolving", label: "Collaborative Problem Solving", group: "Collaboration & Open Source Contribution" },
  { value: "TopContributors", label: "Highlighting Top Contributors", group: "Collaboration & Open Source Contribution" },

  { value: "CodingBootcamps", label: "Organizing Coding Bootcamps", group: "Training & Education" },
  { value: "ContinuousLearning", label: "Providing Resources for Continuous Learning", group: "Training & Education" },
  { value: "KnowledgeSharing", label: "Encouraging Knowledge Sharing", group: "Training & Education" },
];
