export const countries: string[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor (Timor-Leste)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  'Eswatini (fmr. "Swaziland")',
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const popularLanguagesAndTechnologies: {
  focusField: string;
  technologies: string[];
}[] = [
  {
    focusField: "Web Development",
    technologies: [
      "JavaScript",
      "TypeScript",
      "HTML/CSS",
      "React",
      "Angular",
      "Vue.js",
      "Node.js",
      "Express.js",
      "Next.js",
      "Django",
      "Spring",
      "Ruby on Rails",
      "Flask",
      "Laravel",
      "Symfony",
      "ASP.NET",
      "Ember.js",
      "jQuery",
      "Webpack",
      "Babel",
      "Sass/SCSS",
      "Less",
      "GraphQL",
      "RESTful APIs",
      "WebSockets",
      "Progressive Web Apps (PWAs)",
      "WebAssembly",
      "WebRTC",
    ],
  },
  {
    focusField: "Mobile App Development",
    technologies: [
      "React Native",
      "Flutter",
      "SwiftUI",
      "Android (Java/Kotlin)",
      "iOS (Objective-C/Swift)",
      "Xamarin",
      "PhoneGap (Cordova)",
      "Ionic",
      "NativeScript",
      "JavaFX (for mobile)",
      "Kivy (for mobile)",
      "Appcelerator Titanium",
    ],
  },
  {
    focusField: "Desktop App Development",
    technologies: [
      "Electron",
      "Qt",
      "JavaFX (for desktop)",
      "Tkinter",
      "PyQt",
      "WinForms (.NET)",
      "WPF (.NET)",
      "GTK+",
      "Swing (Java)",
      "Avalonia",
    ],
  },
  {
    focusField: "Game Development",
    technologies: [
      "Unity",
      "Unreal Engine",
      "Godot",
      "Cocos2d",
      "Phaser",
      "Three.js",
      "Babylon.js",
      "LibGDX",
      "Corona SDK",
      "LÖVE",
      "Construct",
      "GameMaker Studio",
      "CryEngine",
    ],
  },
  {
    focusField: "Data Science and Machine Learning",
    technologies: [
      "NumPy",
      "Pandas",
      "SciPy",
      "scikit-learn",
      "TensorFlow",
      "Keras",
      "PyTorch",
      "Matplotlib",
      "Seaborn",
      "Plotly",
      "NLTK",
      "Spark",
      "Hadoop",
      "Pyspark",
      "Dask",
      "XGBoost",
      "LightGBM",
      "CatBoost",
      "Prophet",
      "Shiny (R)",
      "Streamlit",
    ],
  },
  {
    focusField: "DevOps and Cloud",
    technologies: [
      "Docker",
      "Kubernetes",
      "AWS",
      "Azure",
      "Google Cloud Platform (GCP)",
      "Jenkins",
      "Git",
      "GitHub",
      "GitLab",
      "Bitbucket",
      "Ansible",
      "Terraform",
      "Prometheus",
      "Grafana",
      "ELK Stack (Elasticsearch, Logstash, Kibana)",
      "Nginx",
      "Apache",
      "Vagrant",
      "Chef",
      "Puppet",
      "SaltStack",
      "OpenStack",
      "Cloud Foundry",
      "Heroku",
      "Serverless Framework",
    ],
  },
  {
    focusField: "Database and SQL",
    technologies: [
      "SQL",
      "MySQL",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "SQLite",
      "Oracle",
      "MariaDB",
      "Cassandra",
      "DynamoDB",
      "Amazon RDS",
      "Elasticsearch",
      "Neo4j",
      "Couchbase",
      "Firebase Realtime Database",
      "Firestore",
      "InfluxDB",
      "TimescaleDB",
      "CockroachDB",
    ],
  },
  {
    focusField: "Blockchain and Cryptocurrency",
    technologies: [
      "Solidity",
      "Web3.js",
      "Truffle",
      "Ganache",
      "Ethers.js",
      "Hyperledger Fabric",
      "Corda",
      "Ripple",
      "Stellar",
      "EOSIO",
      "Bitcoin Core",
      "Ethereum",
      "Binance Smart Chain (BSC)",
      "Polygon (MATIC)",
      "Cardano",
      "Tezos",
    ],
  },
  {
    focusField: "AR/VR Development",
    technologies: [
      "ARKit",
      "ARCore",
      "Vuforia",
      "Unity AR Foundation",
      "A-Frame",
      "Babylon.js XR",
      "WebXR API",
      "Oculus SDK",
      "SteamVR SDK",
      "Viveport SDK",
    ],
  },
  {
    focusField: "IoT Development",
    technologies: [
      "Arduino",
      "Raspberry Pi",
      "MicroPython",
      "Node-RED",
      "MQTT",
      "Particle",
      "Tessel",
      "PlatformIO",
      "AWS IoT Core",
      "Google Cloud IoT Core",
      "Azure IoT Hub",
    ],
  },
  {
    focusField: "Desktop GUI Development",
    technologies: [
      "Electron",
      "Qt",
      "JavaFX",
      "WinForms (.NET)",
      "WPF (.NET)",
      "GTK+",
      "Swing (Java)",
      "Tkinter",
      "PyQt",
      "Avalonia",
    ],
  },
  {
    focusField: "Embedded Systems",
    technologies: [
      "C/C++",
      "Arduino",
      "Raspberry Pi",
      "ARM mbed",
      "FreeRTOS",
      "Zephyr",
      "Contiki",
      "RIOT",
      "TinyOS",
    ],
  },
  {
    focusField: "Functional Programming",
    technologies: [
      "Haskell",
      "Erlang",
      "OCaml",
      "F#",
      "Scala",
      "Clojure",
      "Elm",
      "Elixir",
      "Lisp",
      "Racket",
      "PureScript",
    ],
  },
  {
    focusField: "Quantum Computing",
    technologies: [
      "Q# (Microsoft Quantum)",
      "Cirq (Google)",
      "Qiskit (IBM)",
      "ProjectQ",
      "Quipper",
      "Forest (Rigetti)",
      "Strawberry Fields",
      "Quipper",
      "OpenQL",
    ],
  },
  {
    focusField: "Graphics and UI/UX Design",
    technologies: [
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Adobe XD",
      "Figma",
      "Sketch",
      "InVision",
      "Zeplin",
      "Blender",
      "Maya",
      "3ds Max",
    ],
  },
  {
    focusField: "Natural Language Processing (NLP)",
    technologies: [
      "NLTK",
      "spaCy",
      "Gensim",
      "Hugging Face Transformers",
      "Stanford NLP",
      "OpenNLP",
      "FastText",
      "CoreNLP",
    ],
  },
  {
    focusField: "Robotics",
    technologies: [
      "ROS (Robot Operating System)",
      "Gazebo",
      "PyRobot",
      "Robot Framework",
      "MoveIt!",
      "Orchard Robotics",
      "NAOqi (SoftBank Robotics)",
    ],
  },
  {
    focusField: "Testing and Quality Assurance",
    technologies: [
      "Jest",
      "Mocha",
      "Chai",
      "Selenium",
      "Cypress",
      "JUnit",
      "TestNG",
      "Pytest",
      "Robot Framework",
      "Postman",
      "JUnit",
      "TestNG",
      "Cucumber",
      "Gherkin",
    ],
  },
  {
    focusField: "Version Control",
    technologies: [
      "Git",
      "GitHub",
      "GitLab",
      "Bitbucket",
      "SVN (Subversion)",
      "Mercurial",
    ],
  },
  {
    focusField: "Build and Deployment",
    technologies: [
      "Jenkins",
      "CircleCI",
      "Travis CI",
      "GitLab CI/CD",
      "GitHub Actions",
      "Bamboo",
      "TeamCity",
      "AWS CodePipeline",
      "Azure",
    ],
  },
];
