export const countries: string[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor (Timor-Leste)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  'Eswatini (fmr. "Swaziland")',
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Global",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const techFocusAreas: string[] = [
  "Web Development",
  "Mobile App Development",
  "Data Science",
  "Machine Learning",
  "Cloud Computing",
  "DevOps",
  "Frontend",
  "Backend",
  "Full-Stack",
  "UI/UX Design",
  "Game Development",
  "Artificial Intelligence",
  "Cybersecurity",
  "Blockchain",
  "IoT",
  "Big Data",
  "Linux Administration",
  "Database Management",
  "Network Administration",
  "Microservices",
  "Agile Development",
  "Open Source Contribution",
  "Community Building",
  "Tech Education",
  "Data Engineering",
  "Chatbot Development",
  "Ethical Hacking",
  "Computer Vision",
  "Robotics",
  "Augmented Reality (AR)",
  "Virtual Reality (VR)",
  "Windows Administration",
  "Containerization",
  "Testing and QA",
  "NLP",
  "Low-Code Development",
  "No-Code Development",
  "Bioinformatics",
  "Quantum Computing",
  "Embedded Systems",
  "Digital Signal Processing",
  "High-Performance Computing",
  "Distributed Systems",
  "Geographic Information Systems (GIS)",
  "Wearable Tech",
  "E-commerce Development",
  "Healthcare IT",
  "FinTech",
  "EdTech",
  "GreenTech",
  "Smart Cities",
  "Digital Marketing Tech",
  "E-Government",
  "SpaceTech",
  "TransportTech",
  "Tech Evangelism/Advocacy",
  "Voice Technology",
  "API Development",
  "5G Technology",
  "Serverless Computing",
  "Information Retrieval",
  "Natural Language Generation",
  "Human-Computer Interaction",
  "Semantic Web",
  "Audio Processing",
  "Business Intelligence (BI)",
  "Process Automation",
  "Edge Computing",
  "Threat Intelligence",
  "Real-time Systems",
  "Content Management Systems",
  "Real-time Analytics",
  "Data Visualization",
  "Computational Biology",
  "Speech Recognition",
  "Translation and Localization Tech",
  "Tech Policy and Regulation",
  "Data Privacy and Ethics",
  "Digital Forensics",
  "Wireless Communication Tech",
  "Progressive Web Apps (PWA)",
  "Tech Journalism",
  "Information Architecture",
  "Infrastructure as Code",
  "Systems Integration",
  "VR World Building",
  "Hardware Development",
  "Neural Networks",
  "Reinforcement Learning",
  "Telematics",
  "Motion Capture Technology",
  "Printed Electronics",
  "NanoTech",
  "Optical Computing",
  "Tech Start-up Innovation",
  "AdTech",
  "SaaS Development",
  "RetailTech",
  "AgriTech",
  "Data Center Management",
  "Tech Consulting",
  "Enterprise IT",
  "Web3 and Decentralized Web",
  "Metaverse Development",
  "Graph Computing",
  "Unified Communications",
  "Service-Oriented Architecture",
  "Remote Work Tech",
  "Personal Tech and Gadgets",
  "Tech for Social Good",
  "Digital Art and Design Tech",
  "Tech in Entertainment Industry",
  "CleanTech",
  "SportTech",
  "Other",
];

export const technologies: {
  group: string;
  items: {
    value: string;
    label: string;
  }[];
}[] = [
  // Programming Languages
  {
    group: "Programming Languages",
    items: [
      { value: "JavaScript", label: "JavaScript" },
      { value: "Python", label: "Python" },
      { value: "Java", label: "Java" },
      { value: "PHP", label: "PHP" },
      { value: "C#", label: "C#" },
      { value: "Ruby", label: "Ruby" },
      { value: "TypeScript", label: "TypeScript" },
      { value: "C++", label: "C++" },
      { value: "Go", label: "Go" },
      { value: "Swift", label: "Swift" },
      { value: "Kotlin", label: "Kotlin" },
      { value: "Rust", label: "Rust" },
      { value: "Perl", label: "Perl" },
      { value: "Scala", label: "Scala" },
      { value: "Elixir", label: "Elixir" },
      { value: "Haskell", label: "Haskell" },
      { value: "Lua", label: "Lua" },
      { value: "R", label: "R" },
      { value: "MATLAB", label: "MATLAB" },
      { value: "Dart", label: "Dart" },
      { value: "Objective-C", label: "Objective-C" },
      { value: "Shell", label: "Shell" },
      { value: "Groovy", label: "Groovy" },
      { value: "VHDL", label: "VHDL" },
      { value: "Verilog", label: "Verilog" },
      { value: "COBOL", label: "COBOL" },
      { value: "Fortran", label: "Fortran" },
      { value: "Assembly", label: "Assembly" },
      { value: "Delphi", label: "Delphi" },
      { value: "Julia", label: "Julia" },
      { value: "Clojure", label: "Clojure" },
      { value: "Erlang", label: "Erlang" },
      { value: "OCaml", label: "OCaml" },
      { value: "Scheme", label: "Scheme" },
      { value: "Ada", label: "Ada" },
      { value: "ABAP", label: "ABAP" },
      { value: "Apex", label: "Apex" },
      { value: "Bash", label: "Bash" },
      { value: "C", label: "C" },
      { value: "CoffeeScript", label: "CoffeeScript" },
      { value: "Crystal", label: "Crystal" },
    ],
  },
  {
    group: "Web Development - Frontend",
    items: [
      { value: "React", label: "React" },
      { value: "Angular", label: "Angular" },
      { value: "Vue.js", label: "Vue.js" },
      { value: "Svelte", label: "Svelte" },
      { value: "jQuery", label: "jQuery" },
      { value: "Backbone.js", label: "Backbone.js" },
      { value: "Ember.js", label: "Ember.js" },
      { value: "Preact", label: "Preact" },
      { value: "Aurelia", label: "Aurelia" },
      { value: "Polymer", label: "Polymer" },
      { value: "Meteor", label: "Meteor" },
      { value: "Mithril", label: "Mithril" },
      { value: "Knockout.js", label: "Knockout.js" },
      { value: "Dojo", label: "Dojo" },
      { value: "Nuxt.js", label: "Nuxt.js" },
      { value: "Gatsby", label: "Gatsby" },
      { value: "Sapper", label: "Sapper" },
      { value: "Stencil", label: "Stencil" },
      { value: "Quasar", label: "Quasar" },
      { value: "Alpine.js", label: "Alpine.js" },
      { value: "Blazor", label: "Blazor" },
      { value: "Marko", label: "Marko" },
      { value: "SvelteKit", label: "SvelteKit" },
      { value: "Solid.js", label: "Solid.js" },
      { value: "Stimulus", label: "Stimulus" },
      { value: "Stitches", label: "Stitches" },
      { value: "Tailwind CSS", label: "Tailwind CSS" },
      { value: "Bootstrap", label: "Bootstrap" },
      { value: "Material UI", label: "Material UI" },
      { value: "Bulma", label: "Bulma" },
      { value: "Chakra UI", label: "Chakra UI" },
      { value: "Ant Design", label: "Ant Design" },
      { value: "Foundation", label: "Foundation" },
      { value: "Semantic UI", label: "Semantic UI" },
      { value: "UIKit", label: "UIKit" },
      { value: "PrimeReact", label: "PrimeReact" },
      { value: "Onsen UI", label: "Onsen UI" },
      { value: "React Native Web", label: "React Native Web" },
      { value: "React Bootstrap", label: "React Bootstrap" },
      { value: "React Router", label: "React Router" },
      { value: "React Hook Form", label: "React Hook Form" },
      { value: "React Final Form", label: "React Final Form" },
      { value: "React Redux", label: "React Redux" },
      { value: "React Query", label: "React Query" },
      { value: "React Intl", label: "React Intl" },
      { value: "React Helmet", label: "React Helmet" },
    ],
  },

  // Web Development - Backend Frameworks
  {
    group: "Web Development - Backend",
    items: [
      { value: "Node.js", label: "Node.js" },
      { value: "Express.js", label: "Express.js" },
      { value: "Django", label: "Django" },
      { value: "Laravel", label: "Laravel" },
      { value: "Spring", label: "Spring" },
      { value: "Ruby on Rails", label: "Ruby on Rails" },
      { value: "ASP.NET", label: "ASP.NET" },
      { value: "Flask", label: "Flask" },
      { value: "Symfony", label: "Symfony" },
      { value: "FastAPI", label: "FastAPI" },
      { value: "NestJS", label: "NestJS" },
      { value: "Koa.js", label: "Koa.js" },
      { value: "AdonisJS", label: "AdonisJS" },
      { value: "Strapi", label: "Strapi" },
      { value: "Hapi.js", label: "Hapi.js" },
      { value: "Phoenix (Elixir)", label: "Phoenix (Elixir)" },
      { value: "Play Framework", label: "Play Framework" },
      { value: "LoopBack", label: "LoopBack" },
      { value: "Sails.js", label: "Sails.js" },
      { value: "Moleculer", label: "Moleculer" },
      { value: "Feathers.js", label: "Feathers.js" },
    ],
  },
  {
    group: "Mobile Development",
    items: [
      { value: "React Native", label: "React Native" },
      { value: "Flutter", label: "Flutter" },
      { value: "Ionic", label: "Ionic" },
      { value: "Xamarin", label: "Xamarin" },
    ],
  },
  {
    group: "Quality Assurance",
    items: [
      { value: "JUnit", label: "JUnit" },
      { value: "Selenium", label: "Selenium" },
      { value: "TestNG", label: "TestNG" },
      { value: "Mocha", label: "Mocha" },
      { value: "Chai", label: "Chai" },
      { value: "Jest", label: "Jest" },
      { value: "Cucumber", label: "Cucumber" },
      { value: "Appium", label: "Appium" },
      { value: "Protractor", label: "Protractor" },
      { value: "Postman", label: "Postman" },
      { value: "JIRA", label: "JIRA" },
      { value: "QUnit", label: "QUnit" },
      { value: "LoadRunner", label: "LoadRunner" },
      { value: "Jasmine", label: "Jasmine" },
      { value: "Robot Framework", label: "Robot Framework" },
      { value: "SpecFlow", label: "SpecFlow" },
      { value: "Applitools", label: "Applitools" },
      { value: "WebDriverIO", label: "WebDriverIO" },
      { value: "PyTest", label: "PyTest" },
      { value: "Karma", label: "Karma" },
      { value: "Cypress", label: "Cypress" },
      { value: "Sauce Labs", label: "Sauce Labs" },
      { value: "BrowserStack", label: "BrowserStack" },
      { value: "TestComplete", label: "TestComplete" },
      { value: "TestRail", label: "TestRail" },
      { value: "TestProject", label: "TestProject" },
    ],
  },

  // Database Technologies
  {
    group: "Database Technologies",
    items: [
      { value: "MongoDB", label: "MongoDB" },
      { value: "PostgreSQL", label: "PostgreSQL" },
      { value: "MySQL", label: "MySQL" },
      { value: "MariaDB", label: "MariaDB" },
      { value: "SQLite", label: "SQLite" },
      { value: "Redis", label: "Redis" },
      { value: "Cassandra", label: "Cassandra" },
      { value: "Elasticsearch", label: "Elasticsearch" },
      { value: "Oracle", label: "Oracle" },
      { value: "Microsoft SQL Server", label: "Microsoft SQL Server" },
      { value: "Couchbase", label: "Couchbase" },
      { value: "CouchDB", label: "CouchDB" },
      { value: "Firebase", label: "Firebase" },
      { value: "Neo4j", label: "Neo4j" },
      { value: "Realm", label: "Realm" },
      { value: "RethinkDB", label: "RethinkDB" },
      { value: "ArangoDB", label: "ArangoDB" },
      { value: "DynamoDB", label: "DynamoDB" },
      { value: "FaunaDB", label: "FaunaDB" },
      { value: "HBase", label: "HBase" },
      { value: "InfluxDB", label: "InfluxDB" },
      { value: "Memcached", label: "Memcached" },
      { value: "RavenDB", label: "RavenDB" },
      { value: "Riak", label: "Riak" },
      { value: "Hazelcast", label: "Hazelcast" },
      { value: "Hive", label: "Hive" },
      { value: "PouchDB", label: "PouchDB" },
      { value: "Solr", label: "Solr" },
      { value: "Teradata", label: "Teradata" },
      { value: "VoltDB", label: "VoltDB" },
      { value: "ZooKeeper", label: "ZooKeeper" },
      { value: "CockroachDB", label: "CockroachDB" },
      { value: "H2", label: "H2" },
      { value: "HSQLDB", label: "HSQLDB" },
      { value: "Kafka", label: "Kafka" },
      { value: "Kdb+", label: "Kdb+" },
      { value: "LevelDB", label: "LevelDB" },
      { value: "Lucene", label: "Lucene" },
    ],
  },
  {
    group: "Data Science / Machine Learning",
    items: [
      { value: "TensorFlow", label: "TensorFlow" },
      { value: "PyTorch", label: "PyTorch" },
      { value: "Keras", label: "Keras" },
      { value: "Scikit-learn", label: "Scikit-learn" },
      { value: "Apache Spark", label: "Apache Spark" },
      { value: "Apache Flink", label: "Apache Flink" },
      { value: "Apache Hadoop", label: "Apache Hadoop" },
      { value: "Apache Kafka", label: "Apache Kafka" },
      { value: "Apache Cassandra", label: "Apache Cassandra" },
      { value: "Apache Hive", label: "Apache Hive" },
      { value: "Apache HBase", label: "Apache HBase" },
      { value: "Apache MXNet", label: "Apache MXNet" },
      { value: "Apache Mahout", label: "Apache Mahout" },
      { value: "Apache Pig", label: "Apache Pig" },
      { value: "Pandas", label: "Pandas" },
      { value: "NumPy", label: "NumPy" },
      { value: "SciPy", label: "SciPy" },
      { value: "NLTK", label: "NLTK" },
      { value: "OpenCV", label: "OpenCV" },
      { value: "D3.js", label: "D3.js" },
      { value: "Plotly", label: "Plotly" },
      { value: "Bokeh", label: "Bokeh" },
      { value: "Seaborn", label: "Seaborn" },
      { value: "Matplotlib", label: "Matplotlib" },
      { value: "Altair", label: "Altair" },
      { value: "Shiny", label: "Shiny" },
      { value: "Dash", label: "Dash" },
      { value: "Streamlit", label: "Streamlit" },
      { value: "Scrapy", label: "Scrapy" },
      { value: "Beautiful Soup", label: "Beautiful Soup" },
      { value: "Apache Airflow", label: "Apache Airflow" },
      { value: "Apache Beam", label: "Apache Beam" },
      { value: "Apache Arrow", label: "Apache Arrow" },
    ],
  },

  // DevOps & Deployment
  {
    group: "DevOps & Deployment",
    items: [
      { value: "Docker", label: "Docker" },
      { value: "Kubernetes", label: "Kubernetes" },
      { value: "Ansible", label: "Ansible" },
      { value: "Terraform", label: "Terraform" },
      { value: "Jenkins", label: "Jenkins" },
      { value: "AWS", label: "AWS" },
      { value: "Azure", label: "Azure" },
      { value: "Google Cloud", label: "Google Cloud" },
      { value: "Heroku", label: "Heroku" },
      { value: "Netlify", label: "Netlify" },
      { value: "Vercel", label: "Vercel" },
      { value: "DigitalOcean", label: "DigitalOcean" },
      { value: "Linode", label: "Linode" },
      { value: "Vagrant", label: "Vagrant" },
      { value: "Puppet", label: "Puppet" },
      { value: "Chef", label: "Chef" },
      { value: "SaltStack", label: "SaltStack" },
      { value: "Nginx", label: "Nginx" },
      { value: "Apache", label: "Apache" },
      { value: "HAProxy", label: "HAProxy" },
      { value: "Kong", label: "Kong" },
      { value: "Traefik", label: "Traefik" },
      { value: "Consul", label: "Consul" },
      { value: "Vault", label: "Vault" },
      { value: "Prometheus", label: "Prometheus" },
      { value: "Grafana", label: "Grafana" },
      { value: "ELK Stack", label: "ELK Stack" },
      { value: "Datadog", label: "Datadog" },
      { value: "New Relic", label: "New Relic" },
      { value: "Sentry", label: "Sentry" },
      { value: "Logstash", label: "Logstash" },
      { value: "Kibana", label: "Kibana" },
      { value: "Loggly", label: "Loggly" },
      { value: "Papertrail", label: "Papertrail" },
      { value: "Splunk", label: "Splunk" },
      { value: "LogDNA", label: "LogDNA" },
      { value: "Logz.io", label: "Logz.io" },
      { value: "Sumo Logic", label: "Sumo Logic" },
      { value: "PagerDuty", label: "PagerDuty" },
      { value: "Opsgenie", label: "Opsgenie" },
      { value: "VictorOps", label: "VictorOps" },
      { value: "OpsDash", label: "OpsDash" },
      { value: "Opsmatic", label: "Opsmatic" },
      { value: "Opsview", label: "Opsview" },
    ],
  },
  {
    group: "Other",
    items: [
      { value: "GraphQL", label: "GraphQL" },
      { value: "REST", label: "REST" },
      { value: "gRPC", label: "gRPC" },
      { value: "gRPC-Gateway", label: "gRPC-Gateway" },
      { value: "gRPC-Web", label: "gRPC-Web" },
    ],
  },
  {
    group: "Community Engagement Strategies",
    items: [
      { value: "MemberOnboarding", label: "Member Onboarding & Retention" },
      { value: "CommunityFeedback", label: "Community Feedback Mechanisms" },
      { value: "CommunityCheckIns", label: "Regular Community Check-ins" },
      { value: "CommunityRecognition", label: "Community Member Recognition" },
      { value: "VolunteerPrograms", label: "Volunteer & Ambassador Programs" },
      { value: "EngagementMetrics", label: "Tracking Engagement Metrics" },
    ],
  },
  {
    group: "Content Creation & Sharing",
    items: [
      { value: "Blogging", label: "Blogging & Articles" },
      { value: "Webinars", label: "Webinars & Podcasts" },
      { value: "Tutorials", label: "Tutorials & How-to Guides" },
      { value: "GuestBlogging", label: "Guest Blogging Opportunities" },
      { value: "Infographics", label: "Infographics & Visual Content" },
      { value: "CaseStudies", label: "Publishing Case Studies" },
    ],
  },
  {
    group: "Events & Meetups",
    items: [
      { value: "Hackathons", label: "Hackathons" },
      { value: "Workshops", label: "Workshops" },
      { value: "MeetAndGreets", label: "Community Meet-and-Greets" },
    ],
  },
  {
    group: "Tech Evangelism",
    items: [
      { value: "SpeakingEngagements", label: "Speaking Engagements" },
      { value: "TechRepresentation", label: "Tech Representation at Events" },
      {
        value: "InfluencerRelations",
        label: "Building Relations with Influencers",
      },
    ],
  },
  {
    group: "Mentorship Programs",
    items: [{ value: "Mentorship", label: "Mentorship Programs" }],
  },
  {
    group: "Online Forums & Discussions",
    items: [
      { value: "OnlineAMAs", label: "Hosting AMAs" },
      { value: "TechForums", label: "Participation in Tech Forums" },
      {
        value: "TechDiscussionSpaces",
        label: "Creating Tech Discussion Spaces",
      },
    ],
  },
  {
    group: "Advocacy & Representation",
    items: [
      { value: "DiversityInTech", label: "Ensuring Diversity in Tech" },
      { value: "EthicalTech", label: "Advocating for Ethical Tech" },
      {
        value: "UnderrepresentedCommunities",
        label: "Representing Underserved Communities",
      },
    ],
  },
  {
    group: "Feedback & Iteration",
    items: [
      { value: "TechFeedback", label: "Gathering Tech Feedback" },
      { value: "ProductIteration", label: "Iterating on Products" },
      { value: "BetaTesting", label: "Hosting Beta Testing" },
    ],
  },
  {
    group: "Collaboration & Open Source Contribution",
    items: [
      { value: "OpenSourceContribution", label: "Open Source Contribution" },
      {
        value: "CollaborativeProblemSolving",
        label: "Collaborative Problem Solving",
      },
      { value: "TopContributors", label: "Highlighting Top Contributors" },
    ],
  },
  {
    group: "Training & Education",
    items: [
      { value: "CodingBootcamps", label: "Organizing Coding Bootcamps" },
      {
        value: "ContinuousLearning",
        label: "Providing Resources for Continuous Learning",
      },
      { value: "KnowledgeSharing", label: "Encouraging Knowledge Sharing" },
    ],
  },
  {
    group: "Events & Meetups",
    items: [
      { value: "TechTalks", label: "Tech Talks & Panels" },
      { value: "NetworkingEvents", label: "Networking Events" },
      { value: "DemoDays", label: "Product Demo Days" },
    ],
  },
  {
    group: "Tech Evangelism",
    items: [
      { value: "PartneringWithEducators", label: "Partnering with Educators" },
      { value: "TechProductShowcases", label: "Tech Product Showcases" },
      { value: "TechOutreach", label: "Outreach in Schools & Universities" },
    ],
  },
  {
    group: "Mentorship Programs",
    items: [{ value: "PeerMentorship", label: "Peer-to-peer Mentorship" }],
  },
  {
    group: "Online Forums & Discussions",
    items: [
      { value: "WebForumQAs", label: "Web Forum Q&As" },
      { value: "FocusedGroupDiscussions", label: "Focused Group Discussions" },
    ],
  },
  {
    group: "Advocacy & Representation",
    items: [
      {
        value: "TechAccessibility",
        label: "Advocating for Tech Accessibility",
      },
      {
        value: "SustainableTech",
        label: "Promoting Sustainable Tech Practices",
      },
    ],
  },
  {
    group: "Feedback & Iteration",
    items: [
      { value: "UserInterviews", label: "Conducting User Interviews" },
      { value: "FeatureRequests", label: "Facilitating Feature Requests" },
    ],
  },
  {
    group: "Collaboration & Open Source Contribution",
    items: [
      { value: "CodeReviews", label: "Open Code Reviews" },
      { value: "CommunityDrivenProjects", label: "Community-driven Projects" },
    ],
  },
  {
    group: "Training & Education",
    items: [
      {
        value: "CertificationCourses",
        label: "Offering Certification Courses",
      },
      {
        value: "IndustryInsights",
        label: "Sharing Industry Insights & Trends",
      },
    ],
  },
];
